PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
#Viennese composers and their compositions by tonality
#defaultView:Tree
SELECT ?composer ?composerLabel ?composerImage ?tonality ?tonalityLabel ?composition ?compositionLabel WHERE {
  ?composer wdt:P31 wd:Q5;
            wdt:P19|wdt:P20|wdt:P551 wd:Q1741.
  OPTIONAL { ?composer wdt:P18 ?composerImage. }
  ?composition wdt:P86 ?composer;
               wdt:P826 ?tonality.
OPTIONAL{?composer rdfs:label ?composerde_at . FILTER(LANG(?composerde_at) = "de-at")}
OPTIONAL{?composer rdfs:label ?composerde . FILTER(LANG(?composerde) = "de")}
BIND(str(COALESCE(?composerde_at,?composerde,strafter(str(?composer),"http://www.wikidata.org/entity/"))) AS ?composerLabel)
OPTIONAL{?tonality rdfs:label ?tonalityde_at . FILTER(LANG(?tonalityde_at) = "de-at")}
OPTIONAL{?tonality rdfs:label ?tonalityde . FILTER(LANG(?tonalityde) = "de")}
BIND(str(COALESCE(?tonalityde_at,?tonalityde,strafter(str(?tonality),"http://www.wikidata.org/entity/"))) AS ?tonalityLabel)
OPTIONAL{?composition rdfs:label ?compositionde_at . FILTER(LANG(?compositionde_at) = "de-at")}
OPTIONAL{?composition rdfs:label ?compositionde . FILTER(LANG(?compositionde) = "de")}
BIND(str(COALESCE(?compositionde_at,?compositionde,strafter(str(?composition),"http://www.wikidata.org/entity/"))) AS ?compositionLabel)
}
ORDER BY ?composerLabel ?tonalityLabel ?composer ?composerImage ?tonality ?composition ?compositionLabel
