PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
#People born in Scotland for Listeria
#added before 2016-10
SELECT ?item ?dob
WHERE
{
  	{ ?item wdt:P19 wd:Q22 }
	UNION  { ?item wdt:P19 ?pob . ?pob wdt:P131* wd:Q22 }
        ?item wdt:P31 wd:Q5 .
	OPTIONAL { ?item wdt:P569 ?dob  }
}
ORDER BY ?dob ?item
LIMIT 4000
