PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
#Gender balance of members of Irish parliament
#added before 2016-10
 SELECT ?genderlabel (COUNT(?genderlabel) as ?total)
WHERE
{
   ?subj wdt:P39 wd:Q654291  .
   ?subj wdt:P21 ?gender .
 
   ?gender rdfs:label ?genderlabel filter (lang(?genderlabel) = "en") .
   ?subj rdfs:label ?label filter (lang(?label) = "en")
}
GROUP BY ?genderlabel
ORDER BY ?genderlabel ?total
