PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
#List of parliament buildings with pictures by country
#added before 2016-10
#defaultView:ImageGrid
SELECT ?building ?buildingLabel ?country ?countryLabel ?picture
WHERE
{
	?building wdt:P31 wd:Q7138926 .
	?building wdt:P18 ?picture .
	OPTIONAL { ?building wdt:P17 ?country } .   #if available
	OPTIONAL{?building rdfs:label ?en . FILTER(LANG(?en) = "en")}
	BIND(str(COALESCE(?en,strafter(str(?building),"http://www.wikidata.org/entity/"))) AS ?buildingLabel)
        OPTIONAL{?country rdfs:label ?cen . FILTER(LANG(?cen) = "en")}
	BIND(str(COALESCE(?cen,strafter(str(?country),"http://www.wikidata.org/entity/"))) AS ?countryLabel)
}
ORDER BY ?countryLabel ?building ?buildingLabel ?country ?picture
LIMIT 188
