PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
#Gene and metabolite counts per pathway
SELECT ?pathway ?genes ?metabolites ((?genes/?metabolites) as ?g2m_ratio) WHERE {
{SELECT DISTINCT ?pathway (count(?pwPart) as ?genes) WHERE {
  ?pathway wdt:P2410 ?WikiPathwaysID ;
           wdt:P527 ?pwPart .
  ?pwPart wdt:P31 wd:Q7187 .
  }
GROUP BY ?pathway ?genes }
{SELECT DISTINCT ?pathway (count(?pwPart) as ?metabolites) WHERE {
  ?pathway wdt:P2410 ?WikiPathwaysID ;
           wdt:P527 ?pwPart .
  ?pwPart wdt:P31 wd:Q11173 .
  }
GROUP BY ?pathway ?metabolites}
  }
ORDER BY DESC(?genes) ?pathway ?metabolites ?g2m_ratio
