PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
#Who discovered the most asteroids
SELECT ?discoverer ?name (COUNT(?asteroid) AS ?count)
WHERE
{
	?asteroid wdt:P31 wd:Q3863 .
	?asteroid wdt:P61 ?discoverer .
        OPTIONAL{?discoverer rdfs:label ?en . FILTER(LANG(?en) = "en")}
	BIND(str(COALESCE(?en,strafter(str(?discoverer),"http://www.wikidata.org/entity/"))) AS ?name)
}
GROUP BY ?discoverer ?name
ORDER BY DESC(?count) ?discoverer ?name
LIMIT 20
