PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
#Authors of scientific articles who received a Nobel prize
#added in 2016-10
SELECT ?item ?itemLabel ?person ?personLabel ?image ?award ?awardLabel
WHERE {
  ?person wdt:P166 ?award ; #person received an award
          wdt:P31 wd:Q5 . #person is instance of human
  ?award wdt:P279* wd:Q7191 . #award is a Nobel Prize
  ?item wdt:P50 ?person ; #person is an author of item
        wdt:P31 wd:Q13442814 . #item is a scientific article
  OPTIONAL{?item rdfs:label ?en . FILTER(LANG(?en) = "en")}
	BIND(str(COALESCE(?en,strafter(str(?item),"http://www.wikidata.org/entity/"))) AS ?itemLabel)
  OPTIONAL{?person rdfs:label ?pen . FILTER(LANG(?pen) = "en")}
	BIND(str(COALESCE(?pen,strafter(str(?person),"http://www.wikidata.org/entity/"))) AS ?personLabel)
  OPTIONAL{?award rdfs:label ?aen . FILTER(LANG(?aen) = "en")}
	BIND(str(COALESCE(?aen,strafter(str(?award),"http://www.wikidata.org/entity/"))) AS ?awardLabel)
 
OPTIONAL { ?person wdt:P18 ?image. } #Wikimedia Commons has an image of person
}
ORDER BY ?item ?itemLabel ?person ?personLabel ?image ?award ?awardLabel
