PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
#Biological databases listed in Wikidata and if available applicable licenses
#added before 2016-10
SELECT DISTINCT ?item ?name ?licenseItem ?license
WHERE
{
	?item wdt:P31 wd:Q4117139 ;
          rdfs:label ?name .
    OPTIONAL {?item  wdt:P275 ?licenseItem .
    ?licenseItem rdfs:label ?license .
    FILTER (LANG(?license) = "en")}
    FILTER (LANG(?name) = "en")	
}
ORDER BY ?item ?name ?licenseItem ?license
