PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
#Books by a given Author including genres, series, and publication year
#added before 2016-10
 SELECT ?book ?bookLabel ?authorLabel ?genre_label ?series_label ?publicationDate
WHERE
{
	?author ?label "Ernest Hemmingway"@en .
	?book wdt:P31 wd:Q571 .
	?book wdt:P50 ?author .
	OPTIONAL {
		?book wdt:P136 ?genre .
		?genre rdfs:label ?genre_label filter (lang(?genre_label) = "en").
	}
	OPTIONAL {
		?book wdt:P179 ?series .
		?series rdfs:label ?series_label filter (lang(?series_label) = "en").
	}
	OPTIONAL {
		?book wdt:P577 ?publicationDate .
	}
	OPTIONAL{?book rdfs:label ?en . FILTER(LANG(?en) = "en")}
	BIND(str(COALESCE(?en,strafter(str(?book),"http://www.wikidata.org/entity/"))) AS ?bookLabel)
	OPTIONAL{?author rdfs:label ?aen . FILTER(LANG(?aen) = "en")}
	BIND(str(COALESCE(?aen,strafter(str(?author),"http://www.wikidata.org/entity/"))) AS ?authorLabel)
}
ORDER BY ?book ?bookLabel ?authorLabel ?genre_label ?series_label ?publicationDate
