PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
#List of digital libraries in the world
#added before 2016-10
SELECT DISTINCT ?digitalLibrary  ?digitalLibraryLabel ?website
WHERE
{
	?digitalLibrary wdt:P31 wd:Q212805
	; wdt:P856 ?website .
	OPTIONAL{?digitalLibrary rdfs:label ?en . FILTER(LANG(?en) = "en")}
        OPTIONAL{?digitalLibrary rdfs:label ?es . FILTER(LANG(?es) = "es")}
        OPTIONAL{?digitalLibrary rdfs:label ?de . FILTER(LANG(?de) = "de")}
	BIND(str(COALESCE(?en,?es,?de,strafter(str(?digitalLibrary),"http://www.wikidata.org/entity/"))) AS ?digitalLibraryLabel)
}
ORDER BY ?digitalLibraryLabel ?digitalLibrary ?website
