PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
#Birthplaces of Europeana280 artists
#added before 2016-10
#defaultView:Map
SELECT ?creator ?creatorLabel ?placebirthLabel ?geoloc where {
  ?item wdt:P31/wdt:P279* wd:Q838948 .  # ??uvre d???art et ss-classe
  ?item wdt:P608 wd:Q20980830 . # du projet Europeana 280
  ?item wdt:P170 ?creator . # cr??ateur
  ?creator wdt:P19 ?placebirth . # lieu de naissance
  ?placebirth wdt:P625 ?geoloc . #coordonn??es g??o
  
  OPTIONAL{?creator rdfs:label ?en . FILTER(LANG(?en) = "en")}
        OPTIONAL{?creator rdfs:label ?es . FILTER(LANG(?es) = "es")}
        OPTIONAL{?creator rdfs:label ?fr . FILTER(LANG(?fr) = "fr")}
	BIND(str(COALESCE(?fr,?es,?en,strafter(str(?creator),"http://www.wikidata.org/entity/"))) AS ?creatorLabel)	
	
  OPTIONAL{?placebirth rdfs:label ?pen . FILTER(LANG(?pen) = "en")}
        OPTIONAL{?placebirth rdfs:label ?pes . FILTER(LANG(?pes) = "es")}
        OPTIONAL{?placebirth rdfs:label ?pfr . FILTER(LANG(?pfr) = "fr")}
	BIND(str(COALESCE(?pfr,?pes,?pen,strafter(str(?placebirth),"http://www.wikidata.org/entity/"))) AS ?placebirthLabel)	
}
ORDER BY ?creator ?creatorLabel ?placebirthLabel ?geoloc
