PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
#Get the Reactome citation corups
SELECT ?reactome_id ?item ?itemLabel ?referenceLabel
WHERE
{
	?item wdt:P3937  ?reactome_id ;
          wdt:P2860 ?reference .
   
	OPTIONAL{?item rdfs:label ?en . FILTER(LANG(?en) = "en")}
	BIND(str(COALESCE(?en,strafter(str(?item),"http://www.wikidata.org/entity/"))) AS ?itemLabel)
	OPTIONAL{?reference rdfs:label ?ren . FILTER(LANG(?ren) = "en")}
	BIND(str(COALESCE(?ren,strafter(str(?reference),"http://www.wikidata.org/entity/"))) AS ?referenceLabel)
}
ORDER BY ?reactome_id ?item ?itemLabel ?referenceLabel
