PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
#Items that are simultaneously instance and subclass of the same class
#added before 2016-10
SELECT ?thingLabel ?classLabel ?thing ?class
WHERE
{
	?thing wdt:P31 ?class.
	?thing wdt:P279 ?class.
	OPTIONAL{?thing rdfs:label ?en . FILTER(LANG(?en) = "en")}
	BIND(str(COALESCE(?en,strafter(str(?thing),"http://www.wikidata.org/entity/"))) AS ?thingLabel)
	OPTIONAL{?class rdfs:label ?cen . FILTER(LANG(?cen) = "en")}
	BIND(str(COALESCE(?cen,strafter(str(?class),"http://www.wikidata.org/entity/"))) AS ?classLabel)
}
ORDER BY ?thingLabel ?classLabel ?thing ?class
