PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
#Class distribution of a property
#PS: In the example, the property used is "child (P40)". This can be changed to any other property.
SELECT ?class (COUNT(?subject) AS ?countSubject) WHERE {
  { SELECT DISTINCT ?subject ?class
    WHERE {
      ?subject wdt:P40 ?object .
      ?subject wdt:P31 ?class
    } }
} 
GROUP BY ?class 
ORDER BY DESC(?countSubject) ?class
